version: '3.7'

services:
  node:
    image: 'node:13-alpine'
    container_name: starter-node
    working_dir: /home/node/app
    command: 'npm run start'
    user: node
    ports:
      - 3000:3000
    depends_on:
      - postgres
  postgres:
    image: 'postgres:12-alpine'
    container_name: starter-postgres
    user: postgres
    expose:
      - 5432
    ports:
      - 5432:5432
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 10
